pipelines:
  branches:
    main:
      - step:
          name: Prove AWS access
          image: amazon/aws-cli:latest
          script:
            - aws sts get-caller-identity
            - aws ecr describe-repositories --region $AWS_DEFAULT_REGION

      - step:
          name: Build and Push Docker image to ECR
          image: atlassian/default-image:4
          services:
            - docker
          script:
            - DEBIAN_FRONTEND=noninteractive apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y awscli
            - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
            - docker build -t test-repo .
            - docker tag test-repo:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/test-repo:latest
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/test-repo:latest
